title: "Internet 2016"
tagline: "Take the Pledge: Become an Internet Voter"
fullurl: "https://internet2016.net" #used for fb share content
fbsharetext: "I'm an #InternetVoter. I stand for free speech, access, privacy, choice and openness online. I want all candidates for office to support these principles and create meaningful policies to protect them. Join me and sign the pledge."
fbshareimg: "https://internet2016.net/assets/img/i-heart-the-internet-lawn-sign-tablet-fb.png"
collections:
  toolkits:
permalink: /:categories/:title.html
img_dir: "/assets/img/"
js_dir: "/assets/js/"
css_dir: "/assets/css/"
socialmedia:
  fb: internet2016
  twitter: freepressaction
#baseurl: https://internet2016.net
